### ISSUE TITLE
Documentation: the example is wrong

### ISSUE THREAD

**Issue by shaoran** [shaoran/yagwr#3]
The example is wrong,  it says:

```yaml
---

- condition:
    all:
        - gitlab_token = da89d228826a2ac5ba9abdf438182cfc
          gitlab_event = Push Hook
  action: ~/local/bin/checkout_repo.sh


- condition: path = /a64/logger
  action: python3 ~/local/bin/log_gitlab_event.py > ~/logs/log_gitlab_event.log
```

but it should be

```yaml
---

- condition:
    all:
        - gitlab_token = da89d228826a2ac5ba9abdf438182cfc
        - gitlab_event = Push Hook
  action: ~/local/bin/checkout_repo.sh


- condition: path = /a64/logger
  action: python3 ~/local/bin/log_gitlab_event.py > ~/logs/log_gitlab_event.log
```

See also #2
